apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: mysql
    urumi.io/store-id: {{ .Values.storeId | quote }}
type: Opaque
stringData:
  database: {{ .Values.mysql.auth.database | quote }}
  username: {{ .Values.mysql.auth.username | quote }}
  password: {{ .Values.mysql.auth.password | quote }}
  root-password: {{ .Values.mysql.auth.rootPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: wordpress
    urumi.io/store-id: {{ .Values.storeId | quote }}
type: Opaque
stringData:
  admin-user: {{ .Values.wordpress.adminUser | quote }}
  admin-password: {{ .Values.wordpress.adminPassword | quote }}
  admin-email: {{ .Values.wordpress.adminEmail | quote }}
