apiVersion: v2
name: store
description: Helm chart for provisioning isolated ecommerce stores
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - ecommerce
  - woocommerce
  - wordpress
  - medusa
maintainers:
  - name: Urumi Platform
